kind: Secret
apiVersion: v1
metadata:
  name: git-{{ .Release.Name }}-{{ .Chart.Name }}
data:
  .dockerconfigjson: >-
    {{ .Values.frontend.deployment.gitLabJson }}
type: kubernetes.io/dockerconfigjson 