stages:
  - deploy
deploy-k8s:
  stage: deploy
  image: docker:24.0.7-alpine3.19
  before_script:
    - mkdir ~/.kube
    - echo ${kubeconfig} | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - apk add --no-cache curl bash gnupg helm yq
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
  script:
    - export VERSION=$(yq '.version' helm-chart/Chart.yaml)
    - echo "Install helm version ${VERSION}"
    - helm repo add momo-store ${nexus_helm_url} --username ${nexus_login} --password ${nexus_pass}
    - helm repo list
    - helm repo update
    - helm lint helm-chart
    - helm package helm-chart --destination . 
    - curl -u ${nexus_login}:${nexus_pass} --upload-file momo-store-${VERSION}.tgz ${nexus_helm_url}
    - helm upgrade --install momo-store momo-store-${VERSION}.tgz --create-namespace -n ${NAMESPACE}
    - rm -f ~/.kube/config
  rules:
    - changes:
      - helm-chart/**/*

  environment:
    name: prod
    url: http://momo-store-podionov.ru